Repository wecode-bootcamp-korea/31-1st-kidsney-frontend, pull requests merged in 2022-04, with the labels that each got.

#3 [31기 윤재웅]ADD:목데이터에서 서버통신을 위한 형태로 고도화
  src/Components/Product/Product.js
  src/Pages/ProductList/ProductList.js
  src/config.js
Labels: Status: Accepted

#2 [31기 김효정] 공용 component RecoProduct 생성
  jsconfig.json
  public/data/productData.json
  src/Components/Product/Product.scss
  src/Components/RecoProduct/RecoProduct.js
  src/Components/RecoProduct/RecoProduct.scss
  src/Components/RecoProductList/RecoProductList.js
  src/Components/RecoProductList/RecoProductList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/ProductList/Components/Aside/Aside.scss
  src/Pages/ProductList/Components/SearchItems/SearchItems.scss
  src/Pages/ProductList/Components/SorterBar/SorterBar.scss
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/ProductSpec/ProductSpec.scss
  src/Router.js
  src/Styles/common.scss
  src/index.js
Labels: Status: Accepted

#4 [31기 김보윤] Feature/main 레이아웃 수정
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
Labels: Status: Accepted

#7 [31기 김보윤] Feature/nav 레이아웃 초기세팅 완료 / Conflict 해결 / Review 피드백 반영
  src/Components/Footer/Footer.js
  src/Components/Nav/MenuTab/MenuItems/Boys.js
  src/Components/Nav/MenuTab/MenuItems/Boys.scss
  src/Components/Nav/MenuTab/MenuItems/Girls.js
  src/Components/Nav/MenuTab/MenuItems/Girls.scss
  src/Components/Nav/MenuTab/MenuItems/Toys.js
  src/Components/Nav/MenuTab/MenuItems/Toys.scss
  src/Components/Nav/MenuTab/MenuTab.js
  src/Components/Nav/MenuTab/MenuTab.scss
  src/Components/Nav/Modal/LoginModal.js
  src/Components/Nav/Modal/LoginModal.scss
  src/Components/Nav/Modal/SignUpModal.js
  src/Components/Nav/Modal/SignUpModal.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.scss
  src/Router.js
  src/Styles/common.scss
  src/config.js
Labels: Status: Accepted

#5 [31기 김보윤] Feature/footer 레이아웃 완료 / Conflict 해결 / review 피드백 반영 수정 완료
  src/Components/Footer/Category/Category.js
  src/Components/Footer/Category/Category.scss
  src/Components/Footer/ContentAsset/ContentAsset.js
  src/Components/Footer/ContentAsset/ContentAsset.scss
  src/Components/Footer/ContentCards/ContentCards.js
  src/Components/Footer/ContentCards/ContentCards.scss
  src/Components/Footer/ContentCopyright/ContentCopyright.js
  src/Components/Footer/ContentCopyright/ContentCopyright.scss
  src/Components/Footer/ContentInfo/ContentInfo.js
  src/Components/Footer/ContentInfo/ContentInfo.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.scss
Labels: Status: Accepted

#13 [31기 윤재웅] 다중필터 기능구현 (Type, Character 별필터 완료, Size재고필터는 추가구현사항)
  src/Pages/ProductList/Components/Aside/Aside.js
  src/Pages/ProductList/Components/Aside/Aside.scss
  src/Pages/ProductList/Components/Aside/AsideFilter/AsideFilter.js
  src/Pages/ProductList/Components/Aside/AsideFilter/AsideFilter.scss
  src/Pages/ProductList/ProductList.js
  src/config.js
  src/filterCategory.js
Labels: Status: 리뷰 요청

#9 [31기 김효정] 리뷰 레이아웃 및 기능 구현 완료
  src/Pages/ProductList/ProductSpec/Review/Review.js
  src/Pages/ProductList/ProductSpec/Review/Review.scss
  src/Pages/ProductList/ProductSpec/Review/ReviewModal/ReviewModal.js
  src/Pages/ProductList/ProductSpec/Review/ReviewModal/ReviewModal.scss
  src/Styles/variables.scss
  src/config.js
Labels: Status: Accepted

#11 [31기 윤재웅]SorterBar활용한 가격순&최신순 정렬 구현
  public/data/filterDataBoy.json
  public/data/filterDataGirl copy.json
  public/data/filterDataToy.json
  src/Pages/ProductList/Components/SorterBar/SorterBar.js
  src/Pages/ProductList/Components/SorterBar/SorterBar.scss
  src/Pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#12 [31기 윤재웅]Pagination 기능구현
  src/Pages/ProductList/Components/Pagination/Pagination.js
  src/Pages/ProductList/Components/Pagination/Pagination.scss
  src/Pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#15 [31기 윤재웅] pagination 오류수정
  src/Pages/ProductList/ProductList.js
  src/config.js
Labels: Status: Accepted

#14 [31기 김보윤] Feature/wishList 레이아웃 및 기술 구현 / Conflict 해결 / Review 수정사항 반영
  public/data/productData.json
  public/data/wishProducts.json
  src/Components/Product/Product.js
  src/Components/RecoProductList/RecoProductList.js
  src/Components/RecoProductList/RecoProductList.scss
  src/Components/WishList/EmptyList/EmptyList.js
  src/Components/WishList/EmptyList/EmptyList.scss
  src/Components/WishList/SelectList/SelectList.js
  src/Components/WishList/SelectList/SelectList.scss
  src/Components/WishList/ThemeListImg/ThemeListImg.js
  src/Components/WishList/ThemeListImg/ThemeListImg.scss
  src/Components/WishList/WishList.js
  src/Components/WishList/WishList.scss
  src/Router.js
Labels: Status: Accepted

#8 [31기 김효정] 장바구니 페이지 레이아웃 및 통신 기능 추가
  .vscode/settings.json
  public/data/eventProducts.json
  public/data/orderProducts.json
  public/images/Promotion/creditcard.png
  src/Components/Button/Button.js
  src/Components/Button/Button.scss
  src/Components/Footer/Footer.scss
  src/Components/OrderProduct/OrderProduct.js
  src/Components/OrderProduct/OrderProduct.scss
  src/Pages/MyBag/EditModal/EditModal.js
  src/Pages/MyBag/EditModal/EditModal.scss
  src/Pages/MyBag/MyBag.js
  src/Pages/MyBag/MyBag.scss
  src/Pages/MyBag/OrderSummary/OrderSummary.js
  src/Pages/MyBag/OrderSummary/OrderSummary.scss
  src/Pages/MyBag/SubEvent/SubEvent.js
  src/Pages/MyBag/SubEvent/SubEvent.scss
  src/Pages/ProductList/ProductList.js
  src/Router.js
  src/config.js
Labels: Status: Accepted

#17 [31기 윤재웅]FIX:class -> className으로 오류 수정
  src/Components/Footer/Footer.js
  src/Components/Nav/MenuTab/MenuItems/Boys.js
  src/Components/Nav/MenuTab/MenuItems/Girls.js
Labels: Status: Accepted, Status: 리뷰 요청

#16 [31기 윤재웅]결제기능 구현
  .gitignore
  package-lock.json
  package.json
  src/Pages/Checkout/Checkout.js
  src/Pages/Checkout/Checkout.scss
  src/Pages/Checkout/Component/Order/Order.js
  src/Pages/Checkout/Component/Order/Order.scss
  src/Pages/Checkout/Component/Payment/Payment.js
  src/Pages/Checkout/Component/Payment/Payment.scss
  src/Pages/Checkout/Component/Shipping/Shipping.js
  src/Pages/Checkout/Component/Shipping/Shipping.scss
  src/Pages/ProductList/Components/SearchItems/SearchItems.js
  src/Pages/ProductList/Components/SearchItems/SearchItems.scss
  src/Router.js
  src/config.js
  src/index.js
Labels: Status: Accepted

#18 [31기 김보윤] Feature/nav 레이아웃 수정 / 로그인 전역관리 기능 구현 / Conflict 해결
  src/Components/Nav/MenuTab/MenuItems/Boys.scss
  src/Components/Nav/MenuTab/MenuItems/Girls.scss
  src/Components/Nav/MenuTab/MenuItems/Toys.scss
  src/Components/Nav/MenuTab/MenuTab.scss
  src/Components/Nav/Modal/LoginModal.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/config.js
Labels: Status: Accepted

#19 [31기 김보윤] Feature/main 레이아웃 수정 / Conflict 해결
  src/Components/Nav/MenuTab/MenuItems/Boys.scss
  src/Components/Nav/Modal/LoginModal.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
Labels: Status: Accepted

#20 [31기 김보윤] Feature/wishList 데이터 경로 및 레이아웃 수정 / Review 반영
  src/Components/Product/Product.js
  src/Components/WishList/SelectList/SelectList.js
  src/Components/WishList/SelectList/SelectList.scss
  src/Pages/WishList/EmptyList/EmptyList.js
  src/Pages/WishList/EmptyList/EmptyList.scss
  src/Pages/WishList/SelectList/SelectList.js
  src/Pages/WishList/SelectList/SelectList.scss
  src/Pages/WishList/ThemeListImg/ThemeListImg.js
  src/Pages/WishList/ThemeListImg/ThemeListImg.scss
  src/Pages/WishList/WishList.js
  src/Pages/WishList/WishList.scss
  src/Router.js
Labels: Status: Accepted

#21 [31기 김보윤] Feature/main 레이아웃 scss 수정
  src/Pages/Main/Main.scss
Labels: Status: Accepted

#6 [31기 김효정] product detail 보여주는 컴포넌트 레이아웃 완료 및 기능 추가!
  public/data/orderProducts.json
  public/data/productData.json
  public/images/Promotion/creditcard.png
  public/images/promotion/creditcard.png
  src/Components/Button/Button.scss
  src/Components/OrderProduct/OrderProduct.js
  src/Components/OrderProduct/OrderProduct.scss
  src/Components/Product/Product.js
  src/Components/Product/Product.scss
  src/Components/RecoProductList/RecoProductList.js
  src/Components/RecoProductList/RecoProductList.scss
  src/Pages/Checkout/Checkout.js
  src/Pages/Checkout/Checkout.scss
  src/Pages/Checkout/Component/Order/Order.js
  src/Pages/Checkout/Component/Shipping/Shipping.js
  src/Pages/Main/Main.js
  src/Pages/MyBag/EditModal/EditModal.js
  src/Pages/MyBag/MyBag.js
  src/Pages/MyBag/MyBag.scss
  src/Pages/MyBag/OrderSummary/OrderSummary.js
  src/Pages/MyBag/SubEvent/SubEvent.js
  src/Pages/ProductList/Components/Aside/Aside.js
  src/Pages/ProductList/Components/Aside/Aside.scss
  src/Pages/ProductList/Components/SearchItems/SearchItems.js
  src/Pages/ProductList/Components/SorterBar/SorterBar.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/ProductSpec/MyBagModal/MyBagModal.js
  src/Pages/ProductList/ProductSpec/MyBagModal/MyBagModal.scss
  src/Pages/ProductList/ProductSpec/ProductSpec.js
  src/Pages/ProductList/ProductSpec/ProductSpec.scss
  src/Pages/ProductList/ProductSpec/Review/Review.js
  src/Pages/ProductList/ProductSpec/Review/Review.scss
  src/Pages/ProductList/ProductSpec/Review/ReviewModal/ReviewModal.js
  src/Pages/ProductList/ProductSpec/Review/ReviewModal/ReviewModal.scss
  src/Pages/ProductList/ProductSpec/WishListModal/WishListModal.js
  src/Pages/ProductList/ProductSpec/WishListModal/WishListModal.scss
  src/Pages/WishList/SelectList/SelectList.js
  src/Pages/WishList/SelectList/SelectList.scss
  src/Pages/WishList/WishList.js
  src/Router.js
  src/Styles/common.scss
  src/config.js
Labels: Status: 리뷰 요청

#23 [31기 윤재웅]검색기능 구현
  src/Components/Nav/MenuTab/MenuItems/Boys.js
  src/Components/Nav/MenuTab/MenuItems/Girls.js
  src/Components/Nav/MenuTab/MenuItems/Toys.js
  src/Components/Nav/MenuTab/MenuTab.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/ProductList/Components/SearchItems/SearchItems.js
  src/Pages/ProductList/Components/SorterBar/SorterBar.js
  src/Pages/ProductList/Components/SorterBar/SorterBar.scss
  src/Pages/ProductList/ProductList.js
  src/config.js
Labels: Status: Accepted
